services:
  date:
    image: luckywastaken/result-date
    build:
      dockerfile: date.dockerfile
  result:
    image: luckywastaken/result
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - date
    env_file:
      - .env
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencript
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencript
